-- AlterTable
ALTER TABLE "SalesPlan"
ADD COLUMN "averageTicketSize" DOUBLE PRECISION,
ADD COLUMN "conversionRatio" DOUBLE PRECISION,
ADD COLUMN "existingCustomerContribution" DOUBLE PRECISION,
ADD COLUMN "newCustomerContribution" DOUBLE PRECISION,
ADD COLUMN "monthlyOrderTargets" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN "monthlyLeadTargets" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN "existingCustomerTarget" DOUBLE PRECISION,
ADD COLUMN "newCustomerTarget" DOUBLE PRECISION;
